-- sqlplus / as sysdba @/tmp/CommonDB/PreparatorySQL/2_schema_and_roles.sql

-- create common role
CREATE ROLE MAIN_ROLE;

-- create common schema for data
CREATE USER TIGER
  IDENTIFIED BY common1
  DEFAULT TABLESPACE MAIN_TBS
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFFAULT
  ACCOUNT UNLOCK;
-- 4 Roles for COMMON_SCHEMA
GRANT CONNECT TO TIGER;
GRANT RESOURCE TO TIGER;
GRANT SELECT_CATALOG_ROLE TO TIGER;
GRANT MAIN_ROLE TO TIGER;
ALTER USER TIGER DEFAULT ROLE ALL;

-- create liquibase schema
CREATE USER LIQUIBASE
  IDENTIFIED BY common1
  DEFAULT TABLESPACE MAIN_TBS
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFFAULT
  ACCOUNT UNLOCK;
-- 4 Roles for COMMON_SCHEMA
GRANT CONNECT TO LIQUIBASE;
GRANT DBA TO LIQUIBASE;
ALTER USER LIQUIBASE DEFAULT ROLE ALL;
